### ISSUE TITLE
are you author ,will you support chinese later

### ISSUE THREAD

**Issue by jackylee1** [zhongpei/whisper-word-level-trim#1]
dit-video-by-editing-text

**Comment by zhongpei** [comment]
已经支持中文了，可以直接使用

**Comment by jackylee1** [comment]
那能分离说话人吗



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 26, 2023 09:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhongpei/whisper-word-level-trim] are you author ,will yousupport chinese later (Issue #1)




 
已经支持中文了，可以直接使用
